/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // categories
  categoryMiscellaneous: [
    { type: 'ref', id: 'miscellaneous/index'}
  ],
  categorySoftwareDev: [
    { type: 'ref', id: 'software-development/index'}
  ],
  categorySoftwareQuality: [
      { type: 'ref', id: 'software-quality/index'}
    ],
  categorySoftwareDesign: [
    { type: 'ref', id: 'software-design/index'}
  ],
  // tutorials
  readAndWriteFilesInJava: [
    { type: 'autogenerated',dirName: 'software-development/java/how-to-read-and-write-files-in-java-8'}
  ],
  unitTestingBestPractices: [
    {type: 'autogenerated',dirName: 'software-quality/unit-testing-best-practices'}
  ],
  umlTutorial: [
    {type: 'autogenerated',dirName: 'software-design/uml-tutorial'}
  ]
  

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
