/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // Miscellaneous
  categoryMiscellaneous: [
    { type: 'ref', id: 'miscellaneous/index'}
  ],
  categorySoftwareDev: [
    { type: 'ref', id: 'software-development/index'}
  ],
  categoryCybersecurity: [
    { type: 'ref', id: 'cybersecurity/index'}
  ],
  readAndWriteFilesInJava: [
    { type: 'autogenerated',dirName: 'miscellaneous/how-to-read-and-write-files-in-java-8'}
  ]
  

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
