# This is an appspec.yml template file for use AWS CodeDeploy when deploying on EC2/On-Premises.

version: 0.0
os: linux

files:
  - source: /
    destination: /web/tutoref

permissions:
  - object: /
    pattern: "**"
    owner: www-data
    group: www-data
